Repository Devforlife07/HacktoberFest2020, pull requests merged in 2020-10, with the labels that each got.

#8 Add New Folder Trees
  Trees/BST.cpp
Labels: enhancement, hacktoberfest

#9 Binary Tree to its mirror tree Program
  Trees/Mirror.cpp
Labels: hacktober-accepted, hacktoberfest

#10 Add new Program(Build Binary Tree if Inorder or Preorder Traversal a…
  Trees/BuildBinaryTree.cpp
Labels: hacktober-accepted, hacktoberfest

#11 Added Max Subarray sum
  CSES 2/DP/Max Subarray Sum.cpp
Labels: hacktober-accepted, hacktoberfest

#13 Calculate size of Tree
  Trees/BST.cpp
  Trees/Size.cpp
Labels: hacktober-accepted, hacktoberfest

#14 Add BST case c in Mirror
  Trees/Mirror.cpp
Labels: hacktoberfest-accepted

#15 Add Spiral Form
  Trees/SpiralForm.c
Labels: hacktoberfest-accepted

#16 Add Program to Find Diameter of a Binary Tree
  Trees/Diameter.c
Labels: hacktoberfest-accepted

#17 Added Grid Paths
  CSES 2/DP/Grid Paths.cpp
Labels: hacktoberfest-accepted

#23 Adding Codeforces Submissions
  Codeforces/AgainTwentyFive.java
  Codeforces/AliceAndBob.java
  Codeforces/AmusingJoke.java
  Codeforces/AntonAndDanik.java
  Codeforces/AntonAndPolyhedrons.java
  Codeforces/BearAndBigBrother.java
  Codeforces/BerlandPoker.java
  Codeforces/BetweenTheOffices.java
  Codeforces/BoyOrGirl.java
  Codeforces/BuyingShovels.java
  Codeforces/CME.java
  Codeforces/Candies.java
  Codeforces/Cards.java
  Codeforces/Carsell.java
  Codeforces/ChatRoom.java
  Codeforces/ComparingStrings.java
  Codeforces/DieRoll.java
  Codeforces/DiverseStrings.java
  Codeforces/Drinks.java
  Codeforces/Dubstep.java
  Codeforces/Elephant.java
  Codeforces/ErasingZeroes.java
  Codeforces/EvenOddGame.java
  Codeforces/EvenSubstrings.java
  Codeforces/ExercisingWalk.java
  Codeforces/FafaAndCompany.java
  Codeforces/FastIO copy.java
  Codeforces/FastIO.java
  Codeforces/FileName.java
  Codeforces/FootBall.java
  Codeforces/Football2.java
  Codeforces/FromStoT.java
  Codeforces/GennadyAndCardGame.java
  Codeforces/arrayWithOddSum.java
  Codeforces/cAPSLOCK.java
  Codeforces/covid.java
  Codeforces/divisbility.java
Labels: hacktoberfest-accepted

#24 factorial
  factorial
Labels: hacktoberfest-accepted

#25 Added SPOJ Submissions
  SPOJ/ADDREV.java
  SPOJ/AE00.java
  SPOJ/ALCATRAZ1.java
  SPOJ/BUGLIFE.cpp
  SPOJ/CPTTRN.java
  SPOJ/CPTTRN2.java
  SPOJ/CPTTRN3.java
  SPOJ/FastIO.java
  SPOJ/GDCOFTI.java
  SPOJ/HCOUPLE.java
  SPOJ/LASTDIG.cpp
  SPOJ/LG.java
  SPOJ/MEANSTRIC.java
  SPOJ/MPOW.cpp
  SPOJ/PON.cpp
  SPOJ/PON.java
  SPOJ/PRIME1.cpp
  SPOJ/PRIONPRI.java
  SPOJ/RMQSQ.cpp
  SPOJ/TDKPRIME.cpp
  SPOJ/input.txt
  SPOJ/mytemplate.java
  SPOJ/output.txt
Labels: hacktoberfest-accepted

#27 reverse
  reverse
Labels: hacktoberfest-accepted

#26 pattern
  pattern
Labels: hacktoberfest-accepted

#29 added you a cpp file
  ya.cpp
Labels: hacktoberfest-accepted

#30 added a pancake sort cpp program
  k.cpp
Labels: hacktoberfest-accepted

#31 Create temperature
  temperature
Labels: hacktoberfest-accepted

#32 create calendar.py
  calendar.py
Labels: hacktoberfest-accepted
